classifieds/urls.py
"""
"""
from django.conf.urls.defaults import *

from classifieds.views import AdEditView, AdCreationEditView
from classifieds.views.manage import AdDeleteView


# nested urls
base_urlpatterns = patterns('classifieds.views',
    url(r'^$', 'browse.category_overview',
        name='classifieds_browse_categories'),

    url(r'^post/$', 'create.first_post', name='classifieds_create_ad'),
    url(r'^create/$', 'create.select_category',
        name='classifieds_create_ad_select_category'),
    url(r'^create/(?P<slug>[-\w]+)/$', 'create.create_in_category',
        name='classifieds_create_ad_in_category'),
    url(r'^create/edit/(?P<pk>[0-9]+)/$', AdCreationEditView.as_view(),
        name='classifieds_create_ad_edit'),
    url(r'^create/preview/(?P<pk>[0-9]+)/$', 'create.preview',
        name='classifieds_create_ad_preview'),

    url(r'^search/(?P<slug>[-\w]+)/$', 'browse.search_in_category',
        name='classifieds_browse_category_search'),
    url(r'^search/results/(?P<slug>[-\w]+)/$', 'browse.search_results',
        name='classifieds_browse_search_results'),
    url(r'^(?P<pk>[0-9]+)/$', 'browse.view',
        name='classifieds_browse_ad_view'),
)

# local-based urls coming soon
urlpatterns = base_urlpatterns

# top-level urls
urlpatterns += patterns('classifieds.views',
    url(r'^mine/$', 'manage.mine', name='classifieds_manage_view_all'),
    url(r'^edit/(?P<pk>[0-9]+)/$', AdEditView.as_view(),
        name='classifieds_manage_ad_edit'),
    url(r'^delete/(?P<pk>[0-9]+)/$', AdDeleteView.as_view(),
        name='classifieds_manage_ad_delete'),

    (r'^new/(?P<pk>[0-9]+)/$', 'payment.view_bought'),
    (r'^checkout/(?P<pk>[0-9]+)$', 'payment.checkout'),
    (r'^pricing$', 'payment.pricing'),

    (r'^contact/(?P<pk>[0-9]+)$', 'contact.contact_seller'),
)


from sitemaps import sitemaps


urlpatterns += patterns('',
    (r'^ipn/$', 'paypal.standard.ipn.views.ipn'),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap',
     {'sitemaps': sitemaps}),
)

classifieds/models.py
"""
"""

from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User

# next four lines are for sending the payment email
from django.template import Context, loader
from django.utils.translation import ugettext as _
from django.core.mail import send_mail

from sorl.thumbnail import ImageField

from classifieds.conf import settings

import datetime


class ImageFormat(models.Model):
    format = models.CharField(max_length=10)

    def __unicode__(self):
        return self.format


class Category(models.Model):
    site = models.ForeignKey(Site)
    template_prefix = models.CharField(max_length=200, blank=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    enable_contact_form_upload = models.BooleanField(default=False)
    contact_form_upload_max_size = models.IntegerField(default=2 ** 20)
    contact_form_upload_file_extensions = models.CharField(max_length=200,
                                                     default="txt,doc,odf,pdf")
    images_max_count = models.IntegerField(default=0)
    images_max_width = models.IntegerField(help_text=_(u'Maximum width in pixels.'),
                                           default=1024)
    images_max_height = models.IntegerField(help_text=_(u'Maximum height in pixels.'),
                                            default=1024)
    images_max_size = models.IntegerField(help_text=_(u'Maximum size in bytes.'),
                                          default=2 ** 20)
    images_allowed_formats = models.ManyToManyField(ImageFormat, blank=True)
    description = models.TextField(default='')
    sortby_fields = models.CharField(max_length=200,
                                     help_text=_(u'A comma separated list of field names that should show up as sorting options.'),
                                     blank=True)
    sort_order = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.name + u' Category'

    class Meta:
        verbose_name_plural = u'categories'


class Field(models.Model):
    BOOLEAN_FIELD = 1
    CHAR_FIELD = 2
    DATE_FIELD = 3
    DATETIME_FIELD = 4
    EMAIL_FIELD = 5
    FILE_FIELD = 6
    FLOAT_FIELD = 7
    IMAGE_FIELD = 8
    INTEGER_FIELD = 9
    TIME_FIELD = 10
    URL_FIELD = 11
    TEXT_FIELD = 12
    SELECT_FIELD = 13
    FIELD_CHOICES = (
     (BOOLEAN_FIELD, 'Checkbox'),
     (CHAR_FIELD, 'Text Input (one line)'),
     (DATE_FIELD, 'Date Selector'),
     (DATETIME_FIELD, 'Date and Time Selector'),
     (EMAIL_FIELD, 'Email Address'),
     (FILE_FIELD, 'File Upload'),
     (FLOAT_FIELD, 'Decimal Number'),
     (IMAGE_FIELD, 'Image Upload'),
     (INTEGER_FIELD, 'Integer Number'),
     (TIME_FIELD, 'Time Selector'),
     (URL_FIELD, 'URL Input'),
     (TEXT_FIELD, 'Text Input (multi-line)'),
     (SELECT_FIELD, 'Dropdown List of Options'),
    )
    category = models.ForeignKey(Category, null=True, blank=True)
    name = models.CharField(max_length=100)
    label = models.CharField(max_length=200)
    field_type = models.IntegerField(choices=FIELD_CHOICES)
    help_text = models.TextField(blank=True)
    max_length = models.IntegerField(null=True, blank=True)
    enable_counter = models.BooleanField(help_text=_(u'This enabled the javascript counter script for text fields.'))
    enable_wysiwyg = models.BooleanField(help_text=_(u'This enables the text formatting javascript widget for text fields.'))
    required = models.BooleanField()
    options = models.TextField(help_text=_(u'A comma separated list of options [only for the dropdown list field]'),
                               blank=True)

    def __unicode__(self):
        return self.name + u' field for ' + self.category.name


class Ad(models.Model):
    category = models.ForeignKey(Category)
    user = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    expires_on = models.DateTimeField()
    # active means that the ad was actually created
    active = models.BooleanField()
    title = models.CharField(max_length=255)

    @models.permalink
    def get_absolute_url(self):
        return ('classifieds_browse_ad_view', (self.pk,))

    def __unicode__(self):
        return u'Ad #' + unicode(self.pk) + ' titled "' + self.title + u'" in category ' + self.category.name

    def expired(self):
        if self.expires_on <= datetime.datetime.now():
            return True
        else:
            return False

    def fields(self):
        fields_list = []
        fields = list(self.category.field_set.all())
        fields += list(Field.objects.filter(category=None))

        for field in fields:
            try:
                fields_list.append((field, field.fieldvalue_set.get(ad=self),))
            except FieldValue.DoesNotExist:
                pass  # If no value is associated with that field, skip it.

        return fields_list

    def field(self, name):
        if name == 'title':
            return self.title
        else:
            return FieldValue.objects.get(field__name=name, ad=self).value

    def fields_dict(self):
        fields_dict = {}
        fields_dict['title'] = self.title

        for key, value in self.fields():
            fields_dict[key.name] = value.value

        return fields_dict

    def is_featured(self):
        for payment in self.payment_set.all():
            if payment.paid_on <= datetime.datetime.now() and \
               payment.paid_on + datetime.timedelta(days=payment.pricing.length) >= datetime.datetime.now():
                for option in payment.options.all():
                    if option.name == PricingOptions.FEATURED_LISTING:
                        return True

        return False


class AdImage(models.Model):
    ad = models.ForeignKey(Ad)
    full_photo = ImageField(upload_to='uploads/', blank=True)


class FieldValue(models.Model):
    field = models.ForeignKey(Field)
    ad = models.ForeignKey(Ad)
    value = models.TextField()

    def __unicode__(self):
        return self.value


class Pricing(models.Model):
    length = models.IntegerField(help_text=_(u'Period being payed for in days'))
    price = models.DecimalField(max_digits=9, decimal_places=2)

    def __unicode__(self):
        return u'$' + unicode(self.price) + u' for ' + str(self.length) + u' days'

    class Meta:
        ordering = ['price']
        verbose_name_plural = u'prices'


class PricingOptions(models.Model):
    FEATURED_LISTING = 1
    PRICING_OPTIONS = (
      (FEATURED_LISTING, u'Featured Listing'),
    )
    name = models.IntegerField(choices=PRICING_OPTIONS)
    price = models.DecimalField(max_digits=9, decimal_places=2)

    def __unicode__(self):
        pricing = {}
        pricing.update(self.PRICING_OPTIONS)
        return u'%s for $%s' % (pricing[int(self.name)], self.price,)

    class Meta:
        ordering = ['price']
        verbose_name_plural = u'options'


class ZipCode(models.Model):
    zipcode = models.IntegerField(primary_key=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=2)

    def nearby(self, radius):
        radius = float(radius)
        rangeFactor = 0.014457
        # bounding box
        objs = self.get_queryset().filter(latitude__gte=self.latitude - (radius * rangeFactor),
                                          latitude__lte=self.latitude + (radius * rangeFactor),
                                          longitude__gte=self.longitude - (radius * rangeFactor),
                                          longitude__lte=self.longitude + (radius * rangeFactor))

        # if there are any results left, use GetDistance stored function to finish
        if objs.count() > 0:
            objs = objs.extra(where=['GetDistance(%s,%s,latitude,longitude) <= %s'],
                              params=[self.latitude, self.longitude, radius])

        return objs

    def __unicode__(self):
        return _(u'Zip: %s, City: %s, State: %s') % (unicode(self.zipcode),
                                                     self.city, self.state,)


class Payment(models.Model):
    ad = models.ForeignKey(Ad)
    paid = models.BooleanField(default=False)
    paid_on = models.DateTimeField(null=True)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    pricing = models.ForeignKey(Pricing)
    options = models.ManyToManyField(PricingOptions)

    def complete(self, amount=0.0):
        # clear payment
        if self.amount != amount:
            return False

        self.paid = True
        self.paid_on = datetime.datetime.now()
        self.save()

        # update ad
        self.ad.expires_on += datetime.timedelta(days=payment.pricing.length)
        self.ad.created_on = datetime.datetime.now()
        self.ad.active = True
        self.ad.save()

        # send email for payment
        # 1. render context to email template
        email_template = loader.get_template('classifieds/email/payment.txt')
        context = Context({'payment': self})
        email_contents = email_template.render(context)

        # 2. send email
        send_mail(_('Your payment has been processed.'),
                  email_contents, settings.FROM_EMAIL,
                  [self.ad.user.email], fail_silently=False)


from django.contrib.localflavor.us.models import USStateField, PhoneNumberField


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    receives_new_posting_notices = models.BooleanField(default=False)
    receives_newsletter = models.BooleanField(default=False)
    address = models.CharField(max_length=100, blank=True, default='')
    city = models.CharField(max_length=100, blank=True, default='')
    state = USStateField(blank=True, default='')
    zipcode = models.CharField(max_length=10, blank=True, default='')
    phone = PhoneNumberField(blank=True, default='')

classifieds/views/manage.py
from django.shortcuts import render_to_response, redirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.template import RequestContext
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.views.generic import DeleteView


from classifieds.models import Ad
from classifieds.utils import context_sortable


@login_required
def mine(request):
    ads = Ad.objects.filter(user=request.user, active=True)
    context = context_sortable(request, ads)
    context['sortfields'] = ['id', 'category', 'created_on']
    return render_to_response('classifieds/manage.html', context,
                              context_instance=RequestContext(request))


class AdDeleteView(DeleteView):
    model = Ad

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AdDeleteView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return redirect('classifieds_manage_view_all')

    def delete(self, request, *args, **kwargs):
        response = super(AdDeleteView, self).delete(request, *args, **kwargs)

        # create status message
        messages.success(request, _(u'Ad deleted.'))

        return response

    def get_object(self, queryset=None):
        obj = super(AdDeleteView, self).get_object(queryset)

        if not obj.user == self.request.user:
            raise Http404

        return obj

classifieds/templates/classifieds/ad_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="post" action="#">
        <p>Are you sure you want to delete this ad?</p>
        <p><input type="submit" value="Confirm deletion"> <a href="{% url classifieds_manage_view_all %}">Cancel</a></p>
</form>
{% endblock %}

classifieds/templates/classifieds/category_choice.html
{% extends "base.html" %}
{% load i18n classifieds %}

{% block content %}
 {% block ad_create_status %}
 {% ifequal type "create" %}
  {% post_ad_progress 1 %}
 {% endifequal %}
 {% endblock %}

<ul class="category-list">
{% for category in categories %}
 {% ifequal type "create" %}
 <li><span>{{ category.description }}</span><a class="button" href="{% url classifieds_create_ad_in_category category.slug %}">{{ category.name }}</a></li>
 {% endifequal %}
 {% endfor %}
</ul>
{% endblock %}

classifieds/templates/classifieds/category_overview.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<ul class="category-list">
{% for category in categories %}
<li><span>{{ category.description }}</span><a class="button" href="{% url classifieds_browse_category_search category.slug %}">{% trans 'Search' %} {{ category.name }}</a></li>
{% endfor %}
</ul>
{% endblock content %}

classifieds/templates/classifieds/checkout.html
{% extends "base.html" %}
{% load i18n classifieds %}

{% block extrajs %}
<script type="text/javascript" defer="true" src="{% url classifieds.views.payment.pricing %}"></script>
{% endblock %}

{% block content %}
 {% block ad_create_status %}
  {% post_ad_progress 4 %}
 {% endblock %}
 
 <p>
 {% blocktrans with title=ad.title id=ad.pk category_name=ad.category.name %}
 Checkout page for posting titled "{{ title }}" (Ad Id: {{ id }}) in the {{ category_name }} category.
 {% endblocktrans %}
 </p>

 <form method="post" action="{% url classifieds.views.payment.checkout ad.pk %}">
  {% csrf_token %}
  <table>
   {{ form }}
   <tr>
    <th><label>Total:</label></th>
    <td><div id="total">Choose options above</div></td>
   </tr>
  </table>
  <p style="text-align: center;">
   <input type="image" src="{{ MEDIA_URL }}images/btn_paynowCC_LG.gif" style="border:none;" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
  </p>
 </form>

 <a class="abort-checkout" onclick="return confirm('{% trans 'Are you sure?' %}');" href="{% url classifieds_manage_view_all %}">{% trans 'Exit / Delete' %}</a>

{% endblock %}

classifieds/templates/classifieds/edit.html
{% extends "base.html" %}
{% load i18n classifieds thumbnail %}

{% block head %}
{{ form.media|safe }}
{% endblock %}

{% block sidebar %}
<ul>
 <li><a href="/">Home</a></li>
</ul>
<div class="welcome">Welcome, <span class="name">{{ user.first_name }}</span></div>
<ul class="arrow">
 <li><a href="{% url classifieds.views.create.select_category %}">Post a New Ad</a></li>
 <li><a href="{% url classifieds.views.manage.mine %}">Manage My Ads</a></li>
 <li><a href="{% url profiles_edit_profile %}">My Profile</a></li>
 <li><a href="{% url django.contrib.auth.views.logout %}">Logout</a></li>
</ul>
{% endblock %}

{% block content %}
 {% block ad_create_status %}
  {% if create %}
  {% post_ad_progress 2 %}
  {% endif %}
 {% endblock %}
<p>(<span class="required">*</span> Required Fields)</p>
<form enctype="multipart/form-data" method="post" action="#">
 <table id="adEdit">
  <tr>
   <th>Category:</th>
   <td colspan="3" style="font-weight: bold;">{{ ad.category.name }}</td>
  </tr>
  {% block form %}
  {{ form }}
  {% endblock %}
  <tr>
   <td colspan="4">{{ imagesformset.non_form_errors }}</td>
  </tr>
  {% if imagesformset.forms %}
  <tr>
   <td colspan="4">
    <h3 style="font-size: 16px;">Add Picture(s)</h3>
   </td>
  </tr>
  <tr>
   <td colspan="4">Uploaded images must be smaller than {{ ad.category.images_max_size|filesizeformat }}. Images with dimensions larger than {{ ad.category.images_max_width }} by {{ ad.category.images_max_height }} pixels will be resized. 
   Images must be in one of the following formats:
   {% for format in ad.category.images_allowed_formats.all %}
     {{ format.format }}
   {% endfor %}
   </td>
  </tr>
  {% endif %}
  {% for imageform in imagesformset.forms %}
    <tr>
     <td colspan="4">
      {{ imageform.id }}
      <label>Picture #{{ forloop.counter }}</label> {{ imageform.full_photo }}
      {{ imageform.DELETE.label_tag }}{{ imageform.DELETE }}
      {% if imageform.initial.full_photo %}
       {% thumbnail imageform.initial.full_photo "1000" as big %}
        {% thumbnail imageform.initial.full_photo "50x50" crop="center" as small %}
         <a href="{{ big.url }}" title="View full-size image"><img src="{{ small.url }}" alt="Photo Thumbnail"></a>
        {% endthumbnail %}
       {% endthumbnail %}
      {% endif %}
  	 </td>
  	</tr>
  {% endfor %}
 </table>
 <p style="text-align: right;">
  {{ imagesformset.management_form }}
  <input type="submit" class="submit" value="{% if create %}Create{% else %}Update{% endif %}" />
 </p>
 {% csrf_token %}
</form>
{% endblock %}

classifieds/templates/classifieds/list.html
{% extends "base.html" %}
{% comment %}
  $Id$
{% endcomment %}

{% load humanize %}
{% load thumbnail %}

{% block content %}
{% if category %}
<h2><a href="/">Home</a> &gt; <a href="{% url classifieds.views.browse.search_in_category category.pk %}">Search {{ category.name }}</a> &gt; Search Results</h2>
{% endif %}

{% if no_results %}
 <h2>No results matched your search.</h2>
{% else %}
 {% if page.object_list %}
  {% include "classifieds/sorter.html" %}
  <div class="ads">
  {% for ad in page.object_list %}
   <div class="ad{% if forloop.first %} first{% endif %}{% if ad.is_featured %} featured{% endif %}">
    <div class="description">
    {% if ad.adimage_set.all.0.full_photo %}
     {% thumbnail ad.adimage_set.all.0.full_photo "1000" as big %}
      {% thumbnail ad.adimage_set.all.0.full_photo "50x50" crop="center" as small %}
       <a href="{{ big.url}}" title="View full-size image"><img src="{{ small.url }}" alt="Photo Thumbnail"></a>
      {% endthumbnail %}
     {% endthumbnail %}
    {% else %}
     <span class="img">No Photo</span>
    {% endif %}
     <div class="title">{{ ad.title }}</div>
     <div class="right">
      <ul>
      {% if ad.fields_dict.price %}
       <li>${{ ad.fields_dict.price|intcomma }}</li>
      {% endif %}
      </ul>
      <a href="{% url classifieds_browse_ad_view ad.pk %}">View Details &gt; &gt;</a>
     </div>
     <ul class="arrow">
      <li>{% if ad.fields_dict.city %}{{ ad.fields_dict.city }}, {% endif %}{{ ad.fields_dict.location }}</li>
      <li>Created on : {{ ad.created_on|date:"F jS, Y" }}</li>
     </ul>
    </div>
   {% ifequal ad.user user %}
    <div class="options">
     <span class="label">Ad ID : </span>{{ ad.pk }}&nbsp;|&nbsp;{{ ad.adimage_set.count }} Photos&nbsp;|&nbsp;<a href="{% url classifieds.views.browse.view ad.pk %}">View Details</a>&nbsp;|&nbsp;<a href="{% url classifieds_manage_ad_edit ad.pk %}">Edit Listing</a>&nbsp;|&nbsp;<a onclick="return confirm('Are you sure you want to delete this ad?');" href="{% url classifieds_manage_ad_delete ad.pk %}">Delete Listing</a>&nbsp;|&nbsp;<a href="{% url classifieds.views.payment.checkout ad.pk %}">Renew Listing</a>
    </div>
   {% endifequal %}
   </div>
  {% endfor %}
  </div>
 
  {% include "classifieds/pager.html" %} 
 {% else %}
  <p>You don't have any ads. Post a new ad <a href="{% url classifieds_create_ad_select_category %}">here</a>.
 {% endif %}
{% endif %}
{% endblock %}

classifieds/templates/classifieds/manage.html
{% extends "base.html" %}
{% comment %}
  $Id$
{% endcomment %}

{% load humanize thumbnail %}

{% block sidebar %}
<ul>
 <li><a href="/">Home</a></li>
</ul>
<div class="welcome">Welcome, <span class="name">{{ user.first_name }}</span></div>
<ul class="arrow">
 <li><a href="{% url classifieds_create_ad_select_category %}">Post a New Ad</a></li>
 <li><a href="{% url classifieds_manage_view_all %}">Manage My Ads</a></li>
 <li><a href="{% url profiles_edit_profile %}">My Profile</a></li>
 <li><a href="{% url auth_logout %}">Logout</a></li>
</ul>
{% endblock %}


{% block content %}

 {% if page.object_list %}
  {% include "classifieds/sorter.html" %}
  <div class="ads">
  {% for ad in page.object_list %}
   <div class="ad{% if forloop.first %} first{% endif %}{% if ad.is_featured %} featured{% endif %}">
    <div class="description">
    {% if ad.adimage_set.all.0.full_photo %}
     {% thumbnail ad.adimage_set.all.0.full_photo "1000" as big %}
      {% thumbnail ad.adimage_set.all.0.full_photo "50x50" crop="center" as small %}
       <a href="{{ big.url }}" title="View full-size image"><img src="{{ small.url }}" alt="Photo Thumbnail"></a>
      {% endthumbnail %}
     {% endthumbnail %}
    {% else %}
     <span class="img">No Photo</span>
    {% endif %}
     <div class="title">{{ ad.title }}</div>
     <div class="right">
      <ul>
      {% if ad.fields_dict.price %}
       <li>${{ ad.fields_dict.price|intcomma }}</li>
      {% endif %}
      </ul>
      <a href="{% url classifieds_browse_ad_view ad.pk %}">View Details &gt; &gt;</a>
     </div>
     <ul class="arrow">
      {% if ad.fields_dict.city %}
      <li>{{ ad.fields_dict.city }}</li>
      {% else %}
      <li>{{ ad.fields_dict.location }}</li>
      {% endif %}
      <li>Created on : {{ ad.created_on|date:"F jS, Y" }}</li>
      <li>Expires on : {{ ad.expires_on|date:"F jS, Y" }}</li>
     </ul>
    </div>
   {% ifequal ad.user user %}
    <div class="options">
     <span class="label">Ad ID : </span>{{ ad.pk }}&nbsp;|&nbsp;{{ ad.adimage_set.count }} Photos&nbsp;|&nbsp;<a href="{% url classifieds.views.browse.view ad.pk %}">View Details</a>&nbsp;|&nbsp;<a href="{% url classifieds_manage_ad_edit ad.pk %}">Edit Listing</a>&nbsp;|&nbsp;<a onclick="return confirm('Are you sure you want to delete this ad?');" href="{% url classifieds_manage_ad_delete ad.pk %}">Delete Listing</a>&nbsp;|&nbsp;<a href="{% url classifieds.views.payment.checkout ad.pk %}">Renew Listing</a>
    </div>
   {% endifequal %}
   </div>
  {% endfor %}
  </div>
 
  {% include "classifieds/pager.html" %} 
 {% else %}
  <p>You don't have any ads. Post a new ad <a href="{% url classifieds_create_ad_select_category %}">here</a>.
 {% endif %}

{% endblock %}

classifieds/templates/classifieds/view.html
{% extends "base.html" %}
{% load humanize i18n classifieds thumbnail %}

{% block head %}
 <script type="text/javascript" src="{{ MEDIA_URL }}js/thumbnails.js"></script>
{% endblock %}

{% block content %}
 {% block ad_create_status %}
  {% if create %}
  {% post_ad_progress 3 %}
  {% endif %}
 {% endblock %}

 {% if not create %}
  {% if ad.expired %}
  <h3>This ad has expired</h3>
  {% endif %}
 {% endif %}

 {% block ad %}

<div class="ad-view">
 <ul class="options">
  <li>
   <a href="{% url classifieds.views.browse.search_results ad.category.pk %}">&lt; Back to Results</a>
   </li>
  <li>
   <a href="{% url classifieds.view.contact.contact_seller ad.pk %}">Contact Info</a>
  </li>
  <li>
   <a href="{% url classifieds_manage_ad_edit ad.pk %}">Edit Ad</a>
  </li>
 </ul>
</div>

 <div class="title">{{ ad.title }}</div>

 {% if ad.fields_dict.price %}
 <div class="price">${{ ad.fields_dict.price|intcomma }}</div>
 {% endif %}

 <div class="id">
  <span class="label">ID :</span> {{ ad.pk }}<br />
  <span class="label">Posted on :</span> {{ ad.created_on|date:"F jS, Y" }}
 </div>
 
 {% if ad.fields_dict.city and ad.fields_dict.state and ad.fields_dict.zip_code %}
 <div class="location">{{ ad.fields_dict.city }},{{ ad.fields_dict.state }} {{ ad.fields_dict.zip_code }}</div>
 {% else %}
  {% if ad.fields_dict.zip_code %}
 <div class="location">{{ ad.fields_dict.zip_code }}</div>
  {% endif %}
 {% endif %}
 
 {% if ad.fields_dict.description %}
 <div class="description">
  <h2>Description :</h2>
  {{ ad.fields_dict.description }}
 </div>
 {% endif %}

 <div class="images">
 {% for image in ad.adimage_set.all %}
  {% thumbnail image.full_photo "1000" as big %}
   {% thumbnail image.full_photo "50x50" crop="center" as small %}
    <a href="{{ big.url }}" title="View full-size image"><img src="{{ small.url }}" alt="Photo Thumbnail"></a>
   {% endthumbnail %}
  {% endthumbnail %}
 {% endfor %}
 </div>
</div>
 {% endblock %}
 {% block preview_next %}
  {% if create %}
   <div style="height: 100px;">
    <a class="button" style="margin-left: 73px; margin-right: 10px; float: left;" href="{% url classifieds_create_ad_edit ad.pk %}">Edit Ad</a>
    <a class="button" style="float: left;" href="{% url classifieds.views.payment.checkout ad.pk %}">Continue</a>
   </div>
  {% endif %}
 {% endblock %}
{% endblock %}

{% block tellafriend %}http://{{ site.domain }}{% url classifieds_browse_ad_view ad.pk %}{% endblock %}